name: Docker CI (Build & Push to Docker Hub)

on:
  push:
    branches: ["main", "staging", "Evan_3"]
  pull_request:
    branches: ["main", "staging", "Evan_3"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta (back)
        id: meta_back
        uses: docker/metadata-action@v5
        with:
          images: snowlly/projet_docker-back
          tags: |
            type=raw,value=latest
            type=sha

      - name: Docker meta (front)
        id: meta_front
        uses: docker/metadata-action@v5
        with:
          images: snowlly/projet_docker-front
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Build (and push) back
        uses: docker/build-push-action@v6
        with:
          context: ./netnet
          file: ./netnet/src/back/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta_back.outputs.tags }}
          labels: ${{ steps.meta_back.outputs.labels }}

      - name: Build (and push) front
        uses: docker/build-push-action@v6
        with:
          context: ./netnet/src/front
          file: ./netnet/src/front/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta_front.outputs.tags }}
          labels: ${{ steps.meta_front.outputs.labels }}
